# Generated by Django 5.1.1 on 2024-09-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
